name = "ContinuumModels"
uuid = "3a778109-d974-46c8-ac54-09f30d605bdf"
authors = ["Carson Farmer and Hector Medina"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
